# dev testing deployment - ensure you are at root of git repo.
# deployment windows:   docker stack deploy -c .\dev\stacks\standard.yaml insightdev-standard
# deployment linux:     docker stack deploy -c ./dev/stacks/standard.yaml insightdev-standard

version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    hostname: insightmq
    environment:
      RABBITMQ_DEFAULT_USER: "insight"
      RABBITMQ_DEFAULT_PASS: "insightdev"
      RABBITMQ_DEFAULT_VHOST: "insight"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - insightdev
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
      - target: 15672
        published: 8080
        protocol: tcp
        mode: host
  redis:
    image: redis:6.2.6
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - redis-data:/data
    networks:
      - insightdev
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    command: --requirepass "insightdev" --appendonly yes --appendfsync everysec
networks:
  insightdev:
    driver: overlay
volumes:
  rabbitmq-data:
  redis-data: